### ISSUE TITLE
Add version/release

### ISSUE THREAD

**Issue by dandv** [webix-hub/material-design-skin#2]
I'm creating a Meteor package for this skin and don't know what version number to assign :)

**Comment by mkozhukh** [comment]
Current version is for Webix 2.3.x
I will configure auto-publishing for this repo tomorrow, so it will be auto-updated after each release and will have version tags similar to the main Webix repo

**Comment by dandv** [comment]
Thanks. Will this skin be moved together with the others in the same Webix tracker repo?

**Comment by dandv** [comment]
@mkozhukh: any update after 2.4?

**Comment by dandv** [comment]
Any plans to move this skin together with [the others in the Webix tracker repo](https://github.com/webix-hub/tracker/tree/master/codebase/skins)?

Just curious what makes it special to have its own separate repo.
