### ISSUE TITLE
Demo does not allow pinch to zoom on mobile

### ISSUE THREAD

**Issue by joeblew99** [webix-hub/material-design-skin#7]

**Comment by dandv** [comment]
I'm not sure this has much to do with the skin itself. Have you checked your [`<meta name="viewport">` line](http://stackoverflow.com/questions/13014834/meta-viewport-breaking-pinch-zoom-on-mobile)? Also, more details about the bug would help. And might even elicit a response from @mkozhukh ;)

**Comment by mkozhukh** [comment]
The latest version of Webix (4.0) must-not block the touch actions by default anymore. 
The only exception - if you have a scrollable view ( like list or a datatable with a scroll - zoom actions will not work ) 

By the way, if you are using "webix.ui.fullScreen()", the code will add a meta tag which will prevent page zooming.
